
# Group Tasl

CRUD API.

### Retrieve index [GET /task]

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}

+ Response 200 (application/json)

        {
            "data": [{
                "id": "ID",
                "title": "something...",
                "done": false
            }, {
                "id": "ID",
                "title": "something else ...",
                "done": false
            }]
        }

### Retrieve item [GET /task/{task_id}]

+ Parameters

    + task_id: `ID` (id) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}

+ Response 200 (application/json)

        {
            "data": {
                "id": "ID",
                "title": "do something...",
                "done": false
            }
        }


### Create task [POST /task/create]

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}
            Content-Type: application/json

    + Body

            {
                "data": {
                    "title": "do something...",
                    "done": false
                }
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": "ID",
                "title": "do something...",
                "done": false
            }
        }


### Edit task [POST /task/{task_id}/edit]

+ Parameters

    + task_id: `ID` (id) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}
            Content-Type: application/json

    + Body

            {
                "data": {
                    "title": "do something...",
                    "done": false
                }
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": "ID",
                "title": "do something...",
                "done": false
            }
        }


### Delete task [POST /task/{task_id}/delete]

+ Parameters

    + task_id: `ID` (id) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}

+ Response 200 (application/json)

        {
        }


### Mark as done [POST /task/{task_id}/mark-done]

+ Parameters

    + task_id: `ID` (id) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}
            Content-Type: application/json

    + Body

            {
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": "ID",
                "title": "do something...",
                "done": true
            }
        }


### Mark as undone [POST /task/{task_id}/mark-undone]

+ Parameters

    + task_id: `ID` (id) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}
            Content-Type: application/json

    + Body

            {
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": "ID",
                "title": "do something...",
                "done": false
            }
        }
