
# Group Task

### Retrieve index [GET /client/task]

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}

+ Response 200 (application/json)

        {
            "data": [{
                "id": "ID",
                "title": "something...",
                "done": false
            }, {
                "id": "ID",
                "title": "something else ...",
                "done": false
            }]
        }

### Retrieve item [GET /client/task/{task_id}]

+ Parameters

    + task_id: `ID` (id) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}

+ Response 200 (application/json)

        {
            "data": {
                "id": "ID",
                "title": "do something...",
                "done": false
            }
        }

### Create task [POST /client/task/create]

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}
            Content-Type: application/json

    + Body

            {
                "data": {
                    "title": "do something...",
                    "done": false
                }
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": "ID",
                "title": "do something...",
                "done": false
            }
        }

### Edit task [POST /client/task/{task_id}/edit]

+ Parameters

    + task_id: `ID` (id) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}
            Content-Type: application/json

    + Body

            {
                "data": {
                    "title": "do something...",
                    "done": false
                }
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": "ID",
                "title": "do something...",
                "done": false
            }
        }

+ Response 403 (application/json)

        {
            "code": "Unauthorized",
            "message": "Not authorized"
        }

### Delete task [POST /client/task/{task_id}/delete]

+ Parameters

    + task_id: `ID` (id) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}

+ Response 200 (application/json)

        {
        }

+ Response 403 (application/json)

        {
            "code": "Unauthorized",
            "message": "Not authorized"
        }

### Mark task as done [POST /client/task/{task_id}/done]

+ Parameters

    + task_id: `ID` (id) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}
            Content-Type: application/json

    + Body

            {
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": "ID",
                "title": "do something...",
                "done": true
            }
        }

+ Response 403 (application/json)

        {
            "code": "Unauthorized",
            "message": "Not authorized"
        }


### Mark task as undone [POST /client/task/{task_id}/undone]

+ Parameters

    + task_id: `ID` (id) - item id.

+ Request

    + Headers

            Authorization: Bearer {{ACCESS_TOKEN}}
            Content-Type: application/json

    + Body

            {
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": "ID",
                "title": "do something...",
                "done": false
            }
        }

+ Response 403 (application/json)

        {
            "code": "Unauthorized",
            "message": "Not authorized"
        }
