FORMAT: 1A
HOST: http://api.starter.com

# Starter API

<!-- include(../../app/module/auth/auth.apib) -->

<!-- include(./spec-crud.apib) -->

<!-- include(./spec-indexing.apib) -->

<!-- include(./draft.apib) -->
