FORMAT: 1A
HOST: http://backend.starter.emiketic.com

# Starter API

<!-- include(../../app/module/auth/auth.apib) -->

<!-- include(../../app/module/account/account.apib) -->

<!-- include(../../app/module/task/task.apib) -->

<!-- include(./draft.apib) -->
