
# Group Indexing Specifications

Indexing API with pagination, sorting, and filtering.

## Retrieve tasks [GET /task{?offset,limit,sort,filter}]

+ Parameters
    + offset: `0` (number, optional) - Requested offset.
            + Default: `1`
    + limit: `10` (number, optional) - Page size; number of records to return.
            + Default: `10`
    + sort: `created_at:-1` (string, optional) - Sort configuration.
            + Default: `created_at:-1`
    + filter: `{ "type": "text" }` (string, optional) - Filter query as JSON.
            + Default: null

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": "1",
                    "title": "do something...",
                    "done": true
                }, {
                    "id": "2",
                    "title": "do something else ...",
                    "done": false
                }
            ],
            "meta": {
                "offset": 0,
                "limit": 3,
                "total": 5,
                "sort": {
                  "created_at": -1
                },
                "filter": {
                  "type": "text"
                }
            }
        }

